Support ZendService-ReCaptcha v3
zendframework/zend-captcha pull request #29
Opened 2017-02-10 15:25 UTC by akrabat

This supports v2 of the ReCaptcha API and update the CS standards to zend-coding-standard.

2017-02-12 14:28 UTC, weierophinney requested changes
The changes make sense. However, I have a few concerns about BC; clearly, folks using the service will already have issues, and will need to update their code. However, I think we can minimize the concerns by retaining old methods and config keys, and proxying them to the new equivalents when possible.

2017-02-12 14:28 UTC, weierophinney commented on doc/book/adapters.md
> +- `setSecretKey($key)` and `getSecretKey()` allow you to specify the secret key to
Is this change within *this* component, or within the recaptcha component? If this component, we should likely retain the original methods, have them proxy to the new ones, and mark them deprecated.

2017-02-12 14:28 UTC, weierophinney commented on src/ReCaptcha.php
>              }
For BC purposes, we should support the old keys.

2017-02-12 14:28 UTC, weierophinney commented on test/ReCaptchaTest.php
> +            'secret_key' => 'secretKey',
We'll need to document which keys are no longer supported.

2017-02-13 21:18 UTC, akrabat commented
@weierophinney: Documentation added along with BC methods and keys for `privKey` & `pubKey`.

2017-02-14 15:07 UTC, weierophinney approved these changes
Looks good, @akrabat !

2017-02-14 22:02 UTC, merged